### ISSUE TITLE
Allow user to register, login, and logoff from the app.

### ISSUE THREAD

**Issue by kapremom** [chingu-voyages/v32-geckos-team-03#12]
**__Feature Description__**
Allow user to register, login, and logoff from the app. 

**__Major User Stories/tasks__**
- [ ] Create a user registration component to allow new users to signup
- [ ] Create a component to allow a registered user to login
- [ ] Create a component to allow a logged in user to logout of the app

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
