### ISSUE TITLE
Fetch questions and 4 possible answers from the API

### ISSUE THREAD

**Issue by gordonruby** [chingu-voyages/v32-geckos-team-03#16]
**__Feature Description__**
Fetch questions and 4 possible answers from the API

**__Major User Stories/tasks__**
- [ ] Decide if we want a separate repo for the back end
- [ ] Locate the API that contains the questions and answers
- [ ] Design the database and tables to include topics, questions and answers

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
