### ISSUE TITLE
User can select either a topic or general knowledge

### ISSUE THREAD

**Issue by gordonruby** [chingu-voyages/v32-geckos-team-03#24]
Feature Description:

From the **[Home Page](https://www.figma.com/file/uj3AZSP9UFEOmvxwLx1ICo/Trivia-App-Wireframes?node-id=5%3A184)** the user should be able to choose between starting the general knowledge quiz OR viewing a set of topics. From the home page, either choice would take the user to a different page as seen in the **[Flow Chart](https://www.figma.com/file/zrAoNr2sqNo6sxKknZWvsW/Trivia-App-Flowchart)**.

Major User Stories/tasks:

As a user who has arrived on the home page
I want to be able to select the general knowledge quiz
So that I can take it from the start of the quiz

As a user who has arrived on the home page
I want to be able to navigate to a list of all possible topics
So that I can choose a topic I prefer

Steps:

- [ ] Add the 'general knowledge quiz' elements to the home page, including the BEGIN button
- [ ] Add the 'select a topic' elements to the home page, including the SELECT button
- [ ] Add a hyperlink from the begin button to the /start-quiz page
- [ ] Add a hyperlink from the SELECT button to the /select-a-topic page

Additional Considerations:
[All Wireframes](https://www.figma.com/file/uj3AZSP9UFEOmvxwLx1ICo/Trivia-App-Wireframes?node-id=0%3A1)
[Full Flow Chart](https://www.figma.com/file/zrAoNr2sqNo6sxKknZWvsW/Trivia-App-Flowchart?node-id=0%3A1)
